In [2]:
#Problem 1

import numpy as np
list_ = [ '1' , '2' , '3' , '4', '5' ]
array_list = np.array(object = list_)

In [4]:
print(type(list_))

<class 'list'>


In [5]:
print(type(array_list))

<class 'numpy.ndarray'>


In [9]:
#Problem 2

for i in list_ :
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for i in array_list :
    print(type(i))
    

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
[1 2 3 4 5]


In [10]:
#Problem 3

array_list = np.array(object = list_, dtype = int)

In [14]:
for i in list_ :
    print(type(i))
for i in array_list :
    print(type(i))
    
#Array_list are changed and list elements are type-casted to int and assigned to array_list

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [15]:
#Problem 4

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [18]:
print(np.shape(num_array))

(2, 3)


In [19]:
print(np.size(num_array))

6


In [29]:
#Problem 5

arr = np.zeros([3,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
#Problem 6

arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])